[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "4Hax1x4H4jQjd4xnoutKVDUBbHosoCWVCkKxxMF1STKi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jhuhnke/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
